[workspace]
members = [
    "crates/luna-common",
    "crates/luna-driver",
    "crates/luna-lexer",
    "crates/luna-ast",
    "crates/luna-parser",
    "crates/luna-semantic",
    "crates/luna-mvir",
    "crates/luna-backend",
    "crates/luna-borrowck",
    "crates/luna-llib",
    "crates/luna-optimizer",
    "crates/luna-cli",
]
